config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls',namespace='news')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import *

app_name='news'
urlpatterns = [
  path('',news_list,name='home'),
  path("category/<int:pk>/",category_post,name='category_post'),
  path('detail/<int:pk>/<str:category>/',detail,name='detail'),
  path('news/',news,name='news'),
  path('post/',post_tag,name='post_tag')
  
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from tagging.fields import TagField
from django.urls import reverse
# Create your models here.
#عنوان خبر
class Category(models.Model):
    name=models.CharField(max_length=100)
    status=models.CharField(max_length=2,choices=(('1','Active'),('2','Inactive')),default=1)
    create=models.DateTimeField(auto_now_add=True)
    image=models.ImageField(upload_to='category_img/',blank=True)
    
    def __str__(self):
        return self.name
    
class City(models.Model):
    name=models.CharField(max_length=100)
    def __str__(self):
        return self.name
    

class Post(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,default="")
    city=models.ForeignKey(City,on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    descriptions=RichTextUploadingField()
    banner=models.ImageField(upload_to="news_banner")
    status=models.CharField(max_length=2,choices=(('1','Published'),('2','Unpublished')),default=2)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now=True)
    views=models.PositiveIntegerField(default=0)
    tags=TagField(blank=True)
    def get_absolute_url(self):
        return reverse("news:detail", args=[self.id,self.category.name])
    
    
    
    def __str__(self):
        return self.title

news/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
# from .models import*
from news.models import Category,Post,City
from tagging.models import Tag
# Create your views here.

# def home(request):
#     return render(request,'news/home.html')
    
# class homepageviews(generic.TemplateView):
#     template_name='news/detail.html'

def news_list(request):
    news=Post.objects.all()
    category=Category.objects.all()
    lastest_posts=Post.objects.all().order_by('-created')[:2]
    older_posts=Post.objects.all().order_by('-created')[2:6]
    olderr_posts=Post.objects.all().order_by('-created')[:4]
    populer_posts=Post.objects.order_by('-views')[:2]
    older_populer_posts=Post.objects.order_by('-views')[2:4]
    populerr_posts=Post.objects.order_by('-views')[:5]
    tags=Tag.objects.all()    
    post_tag=Post.objects.filter(tags__in=["طلا",'تصادف','ماشین',"قیمت",'فروش'])
  
    return render(request,'news/home.html',{'news':news,
                                            'category':category,
                                            "lastest_post":lastest_posts,
                                            'older_posts':older_posts,
                                            'olderr_posts':olderr_posts,
                                            'populer_posts':populer_posts,
                                            'older_populer_posts':older_populer_posts,
                                            'populerr_posts':populerr_posts,
                                            'tags':tags,
                                            'post_tag':post_tag,
                                            })

def category_post(request,pk):
    categories=Category.objects.get(id=pk)
    posts=Post.objects.filter(status=1,category=categories)
    tags=Tag.objects.all()
    category=Category.objects.all()
    populerr_posts=Post.objects.order_by('-views')[:5]
    return render(request,'news/category_post.html',{'categories':categories,
                                                     'posts':posts,
                                                      'populerr_posts':populerr_posts,
                                                    'tags':tags,
                                                    'category':category,
                                                     })



def detail(request,pk,category):
    # post=Post.objects.get(id=pk,category__name=category)
    post=get_object_or_404(Post,id=pk,category__name=category)
    post.views+=1
    post.save()
    populerr_posts=Post.objects.order_by('-views')[:5]
    tags=Tag.objects.all()
    category=Category.objects.all()
    return render(request,'news/detail.html',{'post':post,
                                              'populerr_posts':populerr_posts,
                                            'tags':tags,
                                            'category':category,
                                              })



# def home(request):
#     latest_posts =Post.objects.order_by('-created')[:2]
#     older_posts =Post.objects.order_by('-created')[2:6]
#     return render(request,'news/lastpost.html',{'latest_posts': latest_posts,"older_posts":older_posts})




    
def news(request):
    posts=Post.objects.all()
    populerr_posts=Post.objects.order_by('-views')[:5]
    tags=Tag.objects.all()
    category=Category.objects.all()
    return render(request,'news/news.html',{'posts':posts,
                                            'populerr_posts':populerr_posts,
                                            'tags':tags,
                                            'category':category,
                                            })
    
    
def post_tag(request):
   post_tag=Post.objects.filter(tags__in=["طلا",'تصادف','ماشین',"قیمت",'فروش'])
   populerr_posts=Post.objects.order_by('-views')[:5]
   tags=Tag.objects.all()
   category=Category.objects.all()
   return render(request,'news/post_tags.html',{'post_tag':post_tag,
                                                 'populerr_posts':populerr_posts,
                                                 'tags':tags,
                                                 'category':category,})

news/templates/news/category_post.html
{% extends "base.html" %}
{% block title %}{{categories}}{% endblock title %}
{% block context %}
<div class="container-fluid py-3">
    <div class="container">
        <div class="row">
            <div class="col-lg-8" >
                <div class="row">
                    <div class="col-12" >
                            <h1 class="m-0" style='text-align:right;color:red;'>{{categories}}</h1>
                        <hr style='border:3px dotted red;'>
                    </div>
                    {% for post in posts  %}
                    <div class="col-lg-6">
                        <div class="position-relative mb-3">
                            <img src="{{post.banner.url}}" width="350px;" height="250px" >
                            <div class="overlay position-relative bg-light">
                                <div class="mb-2" style="font-size: 14px;">
                                    <a href="">{{post.views}}:تعدادبازید</a>
                                    <span class="px-1">/</span>
                                    <span>{{post.created|date}}</span>
                                </div>
                                <a class="h4" href="">{{post.title}}</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    
                  
                </div>
                
            </div>
        </div>
    </div>             
</div>                   
                

{% endblock context %}

news/templates/news/detail.html
{% extends 'base.html' %}
{% load static %}
{% block context %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="container">
            <nav class="breadcrumb bg-transparent m-0 p-0">
                <a class="breadcrumb-item" href="{% url 'news:home' %}">صفحه اصلی</a>
                <a class="breadcrumb-item" href="{% url 'news:news' %}">دسته بندی اخبار</a>
                {% for cate in category %}
                {% if post.category == cate %}
    
                
         <a class="breadcrumb-item" href="{% url 'news:category_post' cate.id %}">{{post.category}}</a>
                {% endif %}  {% endfor %}
                <span class="breadcrumb-item active">{{post.title}}</span>
            </nav>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- News With Sidebar Start --> 
    <div class="container-fluid py-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <!-- News Detail Start -->
                    <div class="position-relative mb-3">
                        <img class="img-fluid w-100" src="{{post.banner.url}}" style="object-fit: cover;">
                        <div class="overlay position-relative bg-light">
                            <div class="mb-3">
                                <a href="">{{post.category}}</a>
                                <span class="px-1">/</span>
                                <span>{{post.created}}</span>
                           
                           <b>تعدادبازدید:</b>
                                <a href="">{{post.views}}</a>
                                <span class="px-1">/</span>
                                <b>تگ های خبر:</b>
                                <span style="color:red;">{{post.tags}}</span>
                            </div>
                            <div style="text-align:right;">
                                <h3 class="mb-3">{{post.title}}</h3>
                                <p>{{post.descriptions|safe}}</p>
                                
                            </div>
                        </div>
                    </div>
                    <!-- News Detail End --> 

                    <!-- Comment List Start --> 
                    <div class="bg-light mb-3" style="padding: 30px;">
                        <h3 class="mb-4">3 Comments</h3>
                        <div class="media mb-4">
                            <img src="img/user.jpg" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                            <div class="media-body">
                                <h6><a href="">John Doe</a> <small><i>01 Jan 2045</i></small></h6>
                                <p>Diam amet duo labore stet elitr invidunt ea clita ipsum voluptua, tempor labore
                                    accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.
                                    Gubergren clita aliquyam consetetur sadipscing, at tempor amet ipsum diam tempor
                                    consetetur at sit.</p>
                                <button class="btn btn-sm btn-outline-secondary">Reply</button>
                            </div>
                        </div>
                        <div class="media">
                            <img src="img/user.jpg" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                            <div class="media-body">
                                <h6><a href="">John Doe</a> <small><i>01 Jan 2045 at 12:00pm</i></small></h6>
                                <p>Diam amet duo labore stet elitr invidunt ea clita ipsum voluptua, tempor labore
                                    accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.
                                    Gubergren clita aliquyam consetetur sadipscing, at tempor amet ipsum diam tempor
                                    consetetur at sit.</p>
                                <button class="btn btn-sm btn-outline-secondary">Reply</button>
                                <div class="media mt-4">
                                    <img src="img/user.jpg" alt="Image" class="img-fluid mr-3 mt-1"
                                        style="width: 45px;">
                                    <div class="media-body">
                                        <h6><a href="">John Doe</a> <small><i>01 Jan 2045 at 12:00pm</i></small></h6>
                                        <p>Diam amet duo labore stet elitr invidunt ea clita ipsum voluptua, tempor
                                            labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed
                                            eirmod ipsum. Gubergren clita aliquyam consetetur sadipscing, at tempor amet
                                            ipsum diam tempor consetetur at sit.</p>
                                        <button class="btn btn-sm btn-outline-secondary">Reply</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Comment List End -->

                    <!-- Comment Form Start -->
                    <div class="bg-light mb-3" style="padding: 30px;">
                        <h3 class="mb-4">Leave a comment</h3>
                        <form>
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" class="form-control" id="email">
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                <input type="url" class="form-control" id="website">
                            </div>

                            <div class="form-group">
                                <label for="message">Message *</label>
                                <textarea id="message" cols="30" rows="5" class="form-control"></textarea>
                            </div>
                            <div class="form-group mb-0">
                                <input type="submit" value="Leave a comment"
                                    class="btn btn-primary font-weight-semi-bold py-2 px-3">
                            </div>
                        </form>
                    </div>
                    <!-- Comment Form End -->
                </div>

                <div class="col-lg-4 pt-2 pt-lg-0" >
                    <!-- Social Follow Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0" style='text-align:right;'>مارو دنبال کنید </h3>
                        </div>
                       
                        <div class="d-flex mb-3" >
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #0185AE;">
                                <small class="fab fa-linkedin-in mr-2"></small><small>لینکدین</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #C8359D;">
                                <small class="fab fa-instagram mr-2"></small><small>اینستاگرام</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3" >
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #DC472E;">
                                <small class="fab fa-youtube mr-2"></small><small>یوتیوب</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #10002b;">
                                <small class=""><img src="{% static 'icon--color-white@16px.png' %}">  </small><small>اپارات</small>
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->

                    

                

                    <!-- Popular News Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0" style='text-align:right;'>پست های محبوب</h3>
                        </div>
                        {% for post in populerr_posts %}
                        <div class="d-flex mb-3">
                            <img src="{{post.banner.url}}" style="width: 100px; height: 100px; object-fit: cover;">
                            <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                <div class="mb-1" style="font-size: 13px;">
                                    <a href="">{{post.category}}</a>
                                    <span class="px-1">/</span>
                                    <span>{{post.created}}</span>
                                </div>
                                <a class="h6 m-0" href="">{{post.created|date}}</a>
                            </div>
                        </div>{% endfor %}
                       
                     
                     
                      
                    </div>
                    <!-- Popular News End -->

                    <!-- Tags Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">تگ</h3>
                        </div>
                        <div class="d-flex flex-wrap m-n1">
                            {% for tag in tags %}
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">{{tag}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Tags End -->
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- News With Sidebar End -->


  
{% endblock context %}

news/templates/news/lastpost.html
<div class="row" >
    <div class="col-12" >
        <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
            <a class="text-secondary font-weight-medium text-decoration-none" href="">نمایش بیشتر</a>
            <h3 class="m-0">آخرین خبرها</h3>
            
        </div>
    </div>
   <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for post in lastest_post  %}
       <div class="col-lg-6" style="max-width:375px;margin:7px;">
          <div class="position-relative mb-3">
              <img  src="{{post.banner.url}}" width="345px;" height="270px">
              <div class="overlay position-relative bg-light">
                  <div class="mb-2" style="font-size: 14px;">
                     <a href="">{{post.category}}</a>
                     <span class="px-1">/</span>
                      <span>{{post.created|date}}</span>
                   </div>
                   <a class="h4" href="{{post.get_absolute_url}}">{{post.title|truncatewords:4}}</a>
                  
              </div>
          </div>
       </div>{% endfor %}
   

    {% for post in older_posts %}
      <div class="d-flex mb-3" style="max-width:345px;margin:23px;">
        <img src="{{post.banner.url}}" style="width: 100px; height: 100px; object-fit: cover;">
          <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
            <div class="mb-1" style="font-size: 13px;">
                <a href="">{{post.category}}</a>
                <span class="px-1">/</span>
                <span>{{post.created|date}}</span>
            </div>
            <a class="h6 m-0" href="{{post.get_absolute_url}}">{{post.title}}</a>
          </div>
      </div>{% endfor %}
   </div>
</div>
</div>

news/templates/news/news.html
{% extends "base.html" %}
{% block title %}اخبار{% endblock title %}

{% block context %}
<div class="container-fluid py-3">
    <div class="container">
        <div class="row">
            <div class="col-lg-8" >
                <div class="row">
                    <div class="col-12" >
                      
                            <h1 class="m-0" style='text-align:right;color:red;'>دسته بندی اخبار</h1>
                        <hr style='border:3px dotted red;'>
                    </div>
                    {% for cat in category  %}
                    <div class="col-lg-6">
                        <div class="position-relative mb-3">
                            <img src="{{cat.image.url}}" width="350px;" height="250px" >
                            <div class="overlay position-relative bg-light"> 
                                <a class="h4" href="{% url 'news:category_post' cat.id %}">{{cat.name}}</a>
                               
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
                <h1 class="m-0" style='text-align:right;color:red;'>اخبار روز</h1>
                <hr style='border:3px dotted red;'>
                <div class="row">
                    {% for post in posts %}
                    <div class="col-lg-6" >
                        <div class="d-flex mb-3">
                            <img src="{{post.banner.url}}" style="width: 100px; height: 100px; object-fit: cover;">
                            <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                <div class="mb-1" style="font-size: 13px;">
                                    <a href="">{{post.category}}</a>
                                    <span class="px-1">/</span>
                                    <span>{{post.created|date}}</span>
                                </div>
                                <a class="h6 m-0" href="{{post.get_absolute_url}}">{{post.title}}</a>
                            </div>
                        </div>
                    </div>{% endfor %}
                   
                </div>
            </div>
        </div>
    </div>             
</div>             


{% endblock context %}

news/templates/news/partiation/category.html
<div class="col-lg-4">
    <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
        <h4 class="font-weight-bold mb-4">دسته بندی</h4>
        <a class="text-secondary font-weight-medium text-decoration-none" href="">نمایش همه</a>
    </div>
    
    {% for cat in category %}
    <div class="position-relative overflow-hidden mb-3" style="height: 80px;">
       
        <a href="{% url 'news:category_post' cat.id %}" class="overlay align-items-center justify-content-center h3 m-0 text-black bg-white text-decoration-none">
            {{cat.name}}
        </a>
    </div>{% endfor %}
    
   
  
</div>

news/templates/news/partiation/footer.html
{% load static %}
<div class="container-fluid bg-light pt-5 px-sm-3 px-md-5" >
    <div class="row">
        <div class="col-lg-3 col-md-6 mb-5">
            <a href="index.html" class="navbar-brand">
                {% comment %} <h1 class="mb-2 mt-n2 display-5 text-uppercase"><span class="text-primary">Dango</span>News</h1> {% endcomment %}
            <img src="{% static 'djangonews-logo.png' %}" height="80px;" width="250px;">
            </a>
            
            <div class="d-flex justify-content-start mt-4">
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-instagram"></i></a>
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="font-weight-bold mb-4" style='text-align:right;'>دسته بندی</h4>
            <div class="d-flex flex-wrap m-n1" >
                {% for cat in category  %}
                <a href="{% url 'news:category_post' cat.id %}" class="btn btn-sm btn-outline-secondary m-1" >{{cat.name}}</a>
                {% endfor %}
                
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            
            <div class="d-flex flex-wrap m-n1" style='text-align:right;'>
               {% include "news/partiation/tags.html" %}
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="font-weight-bold mb-4" style='text-align:right;'>دسترسی سریع</h4>
            <div class="d-flex flex-column justify-content-start">
                <a class="text-secondary mb-2" href="{% url 'news:home' %}" style='text-align:right;'><i class="fa fa-angle-right text-dark mr-2" ></i>صفحه اصلی</a>
                <a class="text-secondary" href="{% url 'news:news' %}" style='text-align:right;'><i class="fa fa-angle-right text-dark mr-2" ></i>دسته بندی اخبار</a>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid py-4 px-sm-3 px-md-5 bg-dark">
    <p class="m-0 text-center" style='color:white;'>
        &copy;این وب سایت طراحی شده به وسیله 
        <b style='color:#ffbe0b;'> خانم مهشیدشیدایی </b>
        
       
        
    </p>
</div>

news/templates/news/partiation/tags.html
<div class="pb-3">
    <div class="bg-light py-2 px-4 mb-3">
        <h3 class="m-0" style='text-align:right;'>تگ ها</h3>
    </div>
    
    <div class="d-flex flex-wrap m-n1">
        {% for tag in tags %}
        <a href="" class="btn btn-sm btn-outline-secondary m-1">{{tag}}</a>
        {% endfor %}
     </div>    
</div>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}
    
    {% endblock title %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'newsstyle/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">   

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'newsstyle/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'newsstyle/css/style.css' %}" rel="stylesheet">
<style>
    @font-face {
        font-family:'B_Yekan';
        src: url('{% static 'newsstyle/font/B_Yekan/Yekan.ttf' %}');format('truetype');
        font-weight: normal;
        font-style: normal;
    }
  
    body{
        font-family:'B_Yekan';
       
        
    }
 
    
    
</style>
</head>

<body>

    <!-- Topbar Start -->
   {% block Topbar %}{% include "news/partiation/topbar.html" %}{% endblock Topbar %}
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid p-0 mb-3" >
        <nav class="navbar navbar-expand-lg bg-light navbar-light py-2 py-lg-0 px-lg-5" >
            <a href="" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-5 text-uppercase"><span class="text-primary">django</span>news</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse" dir='rtl' >
                <div class="navbar-nav" >
                    <img src="{% static 'djangonews-logo-removebg-preview.png' %}" height="60px;" width="160px;">
                    <a href="{% url 'news:home' %}" class="nav-item nav-link ">صفحه اصلی</a>
                  
                    <a href="{% url 'news:news' %}" class="nav-item nav-link">خبرها</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">دسته بندی اخبار</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            {% for cate in category %}
                             <a href='{% url 'news:category_post' cate.id %}' class="dropdown-item">{{cate}}</a>
                            {% endfor %}
                            
                        </div>
                    </div>
                    
                </div>
            
                {% comment %} <div class="input-group ml-auto" style="width: 100%; max-width: 300px;">
                    <input type="text" class="form-control" placeholder="Keyword">
                    <div class="input-group-append">
                        <button class="input-group-text text-secondary"><i
                                class="fa fa-search"></i></button>
                    </div>
                </div> {% endcomment %}
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    {% block context %}
    
    {% endblock context %}
   

    <!-- Footer Start -->
   {% block footer %}
   {% include "news/partiation/footer.html" %}
   {% endblock footer %}
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-dark back-to-top"><i class="fa fa-angle-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'newsstyle/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'newsstyle/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'newsstyle/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'newsstyle/mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'newsstyle/js/main.js' %}"></script>

</body>

</html>